adding templates for issues
IMAP-Science-Operations-Center/imap_processing pull request #18
Opened 2023-07-07 17:35 UTC by GFMoraga

# Change Summary

## Overview
Adding template for issue

## New Files
algorithim_dev.md, bug_reporting.md

2023-07-10 15:25 UTC, greglucas reviewed
I think this content is good and the PR looks like it is pointing at the right locations!

I think we might want to use `yaml` formatting instead to allow for some more flexibility in how it is rendered with the boxes/text areas?

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

Can you take the content/ideas you have here and convert them over into:
`algorithm_development.yml` and `bug_report.yml`

I think this would help with some of your multi-section pieces here as well and allow drop-downs, optional sections etc...

2023-07-10 15:25 UTC, greglucas commented on .github/issue_templates/Algorithim_development.md
> +    2. No
This section doesn't render quite right in Markdown: 
![image](https://github.com/IMAP-Science-Operations-Center/imap_processing/assets/12417828/93b43579-6f16-4ec7-b328-4dcb7083d783)

Using checkboxes will show "1/2" items completed, so I don't think we want them. Perhaps just remove these and put `<!-- Specify if any dependencies were added -->` as a comment line in here?

2023-07-10 15:25 UTC, greglucas commented on .github/issue_templates/Bug_reporting.md
> +    Where did it occur?
```suggestion
## Description of the issue
```
I'm not sure what you mean by "where" here. Perhaps start this out with letting the user just put in a brief description and then follow with your more precise requests below.

2023-07-10 15:25 UTC, greglucas commented on .github/issue_templates/Bug_reporting.md
> +- [ ] I tried but I couldn't fix it
```suggestion
### Suggested fix?
```
Maybe leave a spot for people to add a suggested fix? But, I don't think we need to know if they tried or not, they can open a PR if they have a fix for it.

2023-07-11 17:53 UTC, tech3371 commented on .github/issue_templates/Bug_reporting.md
> +- [ ] I tried but I couldn't fix it
I agree. We could leave last one out.

2023-07-11 17:53 UTC, tech3371 commented on .github/issue_templates/Algorithim_development.md
> +
We could even break down this section with subsections. Example, we could have subsection such as input data description, algorithm steps or pseudo code, output data descriptions.

2023-07-11 18:56 UTC, maxinelasp commented on .github/issue_templates/Algorithim_development.md
> +### Other Notes:
I'd like to see a section for related issues as well, to encourage people to link them together.

2023-07-11 18:59 UTC, maxinelasp requested changes

2023-07-11 18:59 UTC, maxinelasp commented on .github/issue_templates/Bug_reporting.md
> +### Additional notes
Maybe a section for affected code, processes, or data might be a helpful addition? 
```suggestion
### Additional notes

### Affected areas (code, data, or processes)
```

2023-07-12 17:24 UTC, GFMoraga commented
@greglucas what are the benefits of a .yml and is it as easy as changing the .md to .yml?

2023-07-12 17:25 UTC, GFMoraga commented
@greglucas @tech3371 why does this not specify the whitespace? Can you help me understand this block?

trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

2023-07-12 17:33 UTC, greglucas commented
> @greglucas what are the benefits of a .yml and is it as easy as changing the .md to .yml?

I think that is what it takes to get the nice auto-formatting shown in that link with text-boxes etc. (i.e. GitHub has special handling of these files) But, maybe that can be done with Markdown as well? I don't know, I've just only seen other repos use yml. This is fine for a first cut and if we do want that format it can be a follow-on ticket as well.

> @greglucas @tech3371 why does this not specify the whitespace? Can you help me understand this block?

All files should have a blank line at the end of them. You can also add a comment to your PR to have the bot help you out as well I think, with just this text in a new comment: `pre-commit.ci autofix`

2023-07-12 18:31 UTC, GFMoraga commented
pre-commit.ci autofix

2023-07-12 20:29 UTC, bourque approved these changes

2023-07-14 13:52 UTC, GFMoraga commented
Markdown is two things: (1) a plain text formatting syntax; and (2) a software tool, written in Perl, that converts the plain text formatting to HTML. On the other hand, YAML is detailed as "A straightforward machine parsable data serialization format designed for human readability and interaction". A human-readable data-serialization language. It is commonly used for configuration files but could be used in many applications where data is being stored or transmitted.

2023-07-14 14:52 UTC, maxinelasp approved these changes

2023-07-14 16:45 UTC, merged