Updated naming conventions for CoDICE
IMAP-Science-Operations-Center/imap_processing pull request #334
Opened 2024-02-04 17:21 UTC by bourque

# Change Summary

## Overview
This PR updates the Naming Conventions docs to include the expected instrument and descriptor names for CoDICE, as well as an updated example.

## Updated Files

- `docs/source/development-guide/style-guide/naming-conventions.rst`

2024-02-04 18:43 UTC, greglucas approved these changes
I think this makes sense, but just to verify, I thought the codice team wanted `hi` in the `<descriptor>` field instead of the instrument field?

2024-02-04 18:45 UTC, bourque commented
I will ask about that when I meet with the CoDICE folks tomorrow. These updates reflect what is defined in the latest version of our algorithm document, but perhaps they want to change it.

2024-02-07 18:19 UTC, maxinelasp commented on docs/source/development-guide/style-guide/naming-conventions.rst
> +  ``codice-hi``, ``codice-lo``, ``glows``, ``hi-45``, ``hi-90``, ``hit``, ``idex``, ``lo``, ``mag``, ``swapi``, ``swe``,
From meeting: Should be one instrument "codice" with further distinctions in the descriptor

2024-02-07 18:21 UTC, maxinelasp requested changes
instrument should be only codice

2024-02-07 18:21 UTC, maxinelasp commented on docs/source/development-guide/style-guide/naming-conventions.rst
> +  * CoDICE: ``priority``, ``sw-angular``, ``nsw-angular``, ``hskp``, ``eng``, ``pha``, ``sw-species``, ``nsw-species``, ``omni``, ``sectored``
Products with "lo" or "hi": omni,

2024-02-12 17:25 UTC, bourque commented
Putting this in draft / on hold until I hear back from the CoDICE folks -- I sent around an email about this with Joey, Micheal, and Mihir in attempt to finalize all of this.

2024-02-21 23:24 UTC, bourque commented
Updated this with new instrument name and descriptors based on feedback from Joey. This is ready for review/merge now.

2024-02-22 15:06 UTC, greglucas approved these changes

2024-02-22 16:33 UTC, tech3371 approved these changes

2024-02-22 21:49 UTC, merged