Data access api README/Docs update
IMAP-Science-Operations-Center/imap_processing pull request #744
Opened 2024-08-07 17:52 UTC by anamanica

# Change Summary

## Overview

This PR combines the information in the README for the data access api into the docs.

## New Dependencies

None

## New Files

None

## Deleted Files

None

## Updated Files

- index.rst
   - adding in README information

## Testing
None

2024-08-08 15:31 UTC, bourque commented
Adding @greglucas as a reviewer here since he wrote most of this documentation and may have opinions about this!

2024-08-08 15:32 UTC, bourque commented
Pertains to https://github.com/IMAP-Science-Operations-Center/imap-data-access/issues/75

2024-08-08 15:40 UTC, greglucas approved these changes
I don't have any major opinions on this, so looks good to me.

The one concern I do have is that it'd be nice if we could have one "source" instead of copying the content to two places because they are bound to get out of sync at some point. Is there a way to `.. include:: https://path/to/external_repo/README.md` or something similar to that for referencing an external project file?

2024-08-08 15:47 UTC, bourque reviewed
Thank you for moving this documentation over! Overall this is looking good, but now that I see it all in one place, I am finding the layout a bit confusing and too intermingled with the existing OpenAPI specification part of the documentation.  As such, I have a suggestion for a better layout:

- Data Access API (i.e. the introduction as you currently have it)
  - Command Line Utility
    - To Install 
    - Base Command Argumments
    - Query/search for data (with example from README)
    - Download a file (with example from README)
    - Upload a file (with example from README)
  - Importing as a package (with example from README) 
  - Configuration
    - Data Directory
    - Data Access URL
  - File Validation  
  - Troubleshooting
  - REST API Specification
    - Query OpenAPI specs
    - Download OpenAPI specs
    - Upload API specs

2024-08-08 15:47 UTC, bourque commented on docs/source/data-access-api/index.rst
> +==========
```suggestion
To Install
----------
```

I think these section headers need to be changed to 'subsections'. I notice that the way these are currently defined is messing up the Table of Contents on the main landing page.

2024-08-08 15:50 UTC, bourque commented
> I don't have any major opinions on this, so looks good to me.
> 
> The one concern I do have is that it'd be nice if we could have one "source" instead of copying the content to two places because they are bound to get out of sync at some point. Is there a way to `.. include:: https://path/to/external_repo/README.md` or something similar to that for referencing an external project file?

@greglucas Totally agree, and I think the end goal is to have all of the documentation pertaining to the Data Access API in this RtD page, and then basically have the `imap-data-access` repo `README` just say something like "For documentation how to use this, go to the official docs here". Does that sound good to you?

2024-08-08 17:53 UTC, greglucas commented
> @greglucas Totally agree, and I think the end goal is to have all of the documentation pertaining to the Data Access API in this RtD page, and then basically have the imap-data-access repo README just say something like "For documentation how to use this, go to the official docs here". Does that sound good to you?

I would personally prefer the opposite direction 🤷 I think a package should be standalone if possible and the README should describe whats going on within that package without needing to click somewhere else. I just don't know how feasible any of it is to go either direction.

2024-08-15 19:04 UTC, bourque commented on docs/source/data-access-api/index.rst
> +----------
```suggestion
Command Line Utility
--------------------
To Install
^^^^^^^^^^
```

It looks like these headings (and throughout this document) are still messing up the main RtD page layout. I think these need to be changed to another level 'down' in markdown.

2024-08-15 19:04 UTC, bourque commented on docs/source/data-access-api/index.rst
> +   :include: /query
This part is describing the REST API specification, so it should be moved to under that section.

2024-08-15 19:04 UTC, bourque commented on docs/source/data-access-api/index.rst
> +   :include: /download
Similar to the last comment, this is describing the REST API so should also be moved (same with the `/upload` section.

2024-08-15 21:44 UTC, anamanica commented on docs/source/data-access-api/index.rst
> +----------
Oh! Sorry, Okay. I think I understand what you are saying now! Should I do this with every heading?

2024-08-15 22:04 UTC, bourque commented on docs/source/data-access-api/index.rst
> +----------
Yes, except for the very first one (line 4), which is fine as is.

2024-08-21 20:21 UTC, bourque commented on docs/source/data-access-api/index.rst
Since this document is quite lengthy now and have several sections and subsections, I suggest to add a table of contents somewhere towards the top. (Could be done in a future PR if desired)

2024-08-21 20:37 UTC, bourque requested changes
Thanks for these updates, this is looking really good! As Greg suggested, I think it is worth exploring if we can automatically include the contents of the `imap-data-access` `README` file in here, but that can be explored in a separate PR if you'd like.

I just have a few suggestions to help clarify some areas or make them a bit more readable.

2024-08-21 20:37 UTC, bourque commented on docs/source/data-access-api/index.rst
Since this document is quite lengthy now and have several sections and subsections, I suggest to add a table of contents somewhere towards the top. (Could be done in a future PR if desired)

2024-08-21 20:37 UTC, bourque commented on docs/source/data-access-api/index.rst
>  interacting with the API. It is the preferred way to use the API.
```suggestion
repository provides a command-line utility and python package for
interacting with the API programmatically. It is the preferred way to use the API.
```

2024-08-21 20:37 UTC, bourque commented on docs/source/data-access-api/index.rst
> +The SDC also provides a REST API that allows users to upload and download files as
I suggest to change this whole paragraph to something like this:

```suggestion
Users may also download, upload, and query via the REST API directly through the browser or `curl` commands. The [REST API Specification](link) section below describes the various endpoints that are supported and how to use them.
```

2024-08-21 20:37 UTC, bourque commented on docs/source/data-access-api/index.rst
> +        [{'file_path': 'imap/swe/l0/2024/01/imap_swe_l0_sci_20240105_v001.pkts', 'instrument': 'swe', 'data_level': 'l0', 'descriptor': 'sci', 'start_date': '20240105', 'version': 'v001', 'extension'
Could you split this up into multiple lines? The way this is displayed on the page (one long line that you have to scroll through) is a bit difficult to see.

2024-08-21 20:37 UTC, bourque commented on docs/source/data-access-api/index.rst
> +To download files using the CLI tool, use the command ``download``. These will be placed in a ``data`` directory.
```suggestion
To download files using the CLI tool, use the command ``download``. The downloaded files will be placed in a ``data`` directory.
```

2024-08-21 20:37 UTC, bourque commented on docs/source/data-access-api/index.rst
> +organize the downloaded files. See the example path: ``data/imap/swe/l0/2024/01/imap_swe_l0_sci_20240105_20240105_v00-01.pkts``
```suggestion
organize the downloaded files. See the example path: ``data/imap/swe/l0/2024/01/imap_swe_l0_sci_20240105_20240105_v00-01.pkts``. The ``data`` directory and its structure is futher described [here](<link to data directory section>)
```

2024-08-21 20:37 UTC, bourque commented on docs/source/data-access-api/index.rst
> +        # [{'file_path': 'imap/swe/l0/2024/01/imap_swe_l0_sci_20240105_v001.pkts', 'instrument': 'swe', 'data_level': 'l0', 'descriptor': 'sci', 'start_date': '20240105','version': 'v001', 'extension
Similar to my comment above, if this could be split into multiple lines I think that would read better

2024-08-21 20:37 UTC, bourque commented on docs/source/data-access-api/index.rst
> +A user's root data location can be specified as an environment variable IMAP_DATA_DIR or through a configuration dictionary within the package itself imap_data_access.config["DATA_DIR"]. If the IMAP_
```suggestion
A user's root data location can be specified as an environment variable ``IMAP_DATA_DIR`` or through a configuration dictionary within the package itself (``imap_data_access.config["DATA_DIR"]``). If the ``IMAP_DATA_DIR`` variable is not set, the program defaults to the user's current working directory + ``data/``.
```

2024-08-21 20:37 UTC, bourque commented on docs/source/data-access-api/index.rst
> +To change the default URL that the package accesses, you can set the environment variable ``IMAP_DATA_ACCESS_URL`` or within the package ``imap_data_access.config["DATA_ACCESS_URL"]``. The default is
```suggestion
To change the default URL that the package accesses, you can set the environment variable ``IMAP_DATA_ACCESS_URL`` or within the package ``imap_data_access.config["DATA_ACCESS_URL"]``. The default is the development server (``https://api.dev.imap-mission.com``).
```

2024-08-21 20:37 UTC, bourque commented on docs/source/data-access-api/index.rst
> +This package validates filenames and paths to check they follow our standards, as defined by the filename conventions. There is also a class available for use by other packages to create filepaths an
```suggestion
This package validates filenames and paths to check they follow our standards, as defined by the [filename conventions](https://imap-processing.readthedocs.io/en/latest/development-guide/style-guide/naming-conventions.html). There is also a class available for use by other packages to create filepaths and filenames that follow the IMAP SDC conventions.
```

2024-08-30 02:10 UTC, bourque commented on docs/source/data-access-api/index.rst
Nevermind, Ana pointed out to me that there is a built-in table of contents on ReadTheDocs, which I totally missed!

2024-08-30 02:11 UTC, bourque approved these changes
Thanks for making those updates, this looks good to go!

2024-09-16 16:36 UTC, bourque commented
@anamanica Just a heads up that you will likely run into merge conflicts once #844 is merged, since that PR is changing the directory names a bit.

2024-10-14 15:06 UTC, maxinelasp commented
@anamanica are you planning on merging this soon?

2025-02-14 18:50 UTC, greglucas commented
@anamanica, are you going to come back to this, or did you want someone else to try and pick it up?

2025-08-21 15:46 UTC, greglucas commented
Closing this for lack of response. I think we can re-open it later if need be or another branch can be opened because there are conflicts.

2025-08-21 15:46 UTC, closed without merging