[WIP] Idex l2
IMAP-Science-Operations-Center/imap_processing pull request #751
Opened 2024-08-15 20:29 UTC by anamanica

# Change Summary

## Overview

Placing idex l2 code into repository and creating l2 `.yaml` files.

## New Dependencies

None

## New Files

- idex_l2.py
   - Python file to hold processing code for l2 data products for IDEX.
- test_idex_l2.py
    - File for testing idex_l2.py [Not implemented yet, perhaps in a different ticket.]

## Deleted Files

None

## Updated Files

None

## Testing

Closes #575

2024-08-21 21:00 UTC, bourque requested changes
This is looking great!

I didn't spend much effort reviewing the actual L2 algorithm itself (I still need to get a better understanding of this myself before I feel like I can comment on it). And this is an initial pass anyways, so we can tackle the algorithm component in a future PR. But I do have a few suggestions for organizing the code.

2024-08-21 21:00 UTC, bourque commented on imap_processing/idex/constants.py
> +"""Contains dataclasses to support IDEX processing."""
```suggestion
"""Contains constants to support IDEX processing."""
```

2024-08-21 21:00 UTC, bourque commented on imap_processing/idex/constants.py
> +ION_GRID_CALIBRATION = 0.00026148
I don't see this one being used anywhere in the code. Perhaps that part just isn't implemented yet? Otherwise it could be removed if it is not used.

2024-08-21 21:00 UTC, bourque commented on imap_processing/idex/constants.py
> +TOF_Low_Peak_Prominence = 7
```suggestion
TIME_OF_IMPACT_INIT = 20
CONSTANT_OFFSET_INIT = 0.0
RISE_TIME_INIT = 3.71
DISCHARGE_TIME_INIT = 37.1
FILLVAL = -1.0e31
TOF_LOW_PEAK_PROMINENCE = 7
```

Suggest to change this in order to be consistently using capitalized variables for constants (which is also suggested by PEP8)

2024-08-21 21:00 UTC, bourque commented on imap_processing/cdf/config/imap_idex_l2_variable_attrs.yaml
Without knowing how accurate the values/contents of these are, the structure and organization of the file looks good to me!

2024-08-21 21:00 UTC, bourque commented on imap_processing/tests/idex/test_idex_l2.py
> +    return write_cdf(decom_test_data)
Since these tests are redundant with what is tested in `test_idex_l1.py`, I suggest to remove these test functions, save a copy of an IDEX L1 file in the `imap_processing/tests/idex/` folder (alongside the test L0 file), and instead write a fixture function here that returns the path to that L1 file. That fixture can then be used by `test_l1_xarray()` test to process the L1 file.

2024-08-21 21:00 UTC, bourque commented on imap_processing/tests/idex/test_idex_l2.py
> +def test_l1_xarray(l1_cdf):
This kind of reads to me like its a test that is testing the L1 code, not the L2 code. So I suggest to rename this to something like:

```suggestion
def test_l2_processing(l1_cdf):
```

2024-08-21 21:00 UTC, bourque commented on imap_processing/tests/idex/test_idex_l2.py
> +    assert l1_data == load_cdf(l1_cdf)
```suggestion
    l2_data = L2Processor(l1_cdf, "v001").l1_data
    assert l2_data == load_cdf(l1_cdf)
```

I think we want to label this as L2 data since it is what is coming out of the L2 pipeline?

2024-08-21 21:00 UTC, bourque commented on imap_processing/idex/l2/idex_l2.py
> +            y = impact.data - np.mean(impact.data[0:10])
I would like to get in the habit of using more descriptive variable names than single characters. I'm not that familiar with the algorithm yet so I don't have a good suggestion right now, but if you can think of a better name for these, that would be welcomed! (Same for the other instances of this in this module)

2025-02-14 18:52 UTC, greglucas commented
@lacoak21, how does this fit in with your IDEX L2 work? Is this still needed or should it be updated?

2025-02-14 19:09 UTC, lacoak21 commented
This is no longer needed! I think too much had changed since Bryan wrote this so it was easier to start fresh.

2025-02-14 19:57 UTC, greglucas commented
Closing per the comment above about the external code having changed significantly since the last update.

2025-02-14 19:57 UTC, closed without merging